/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/hoodie.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.model002_1.geometry} material={materials.front} />
        <mesh geometry={nodes.model002_2.geometry} material={materials.back} />
        <mesh geometry={nodes.model002_3.geometry} material={materials.hood} />
      </group>
    </group>
  )
}

useGLTF.preload('/hoodie.glb')
