/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/tshirt2.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.05}>
        <mesh geometry={nodes.Shirt_1.geometry} material={materials.body} />
        <mesh geometry={nodes.Shirt_2.geometry} material={materials.lowerSleeve} />
        <mesh geometry={nodes.Shirt_3.geometry} material={materials.upperSleeve} />
        <mesh geometry={nodes.Shirt_4.geometry} material={materials.belt} />
        <mesh geometry={nodes.Shirt_5.geometry} material={materials.collar} />
        <mesh geometry={nodes.Shirt_6.geometry} material={materials.bottomBase} />
        <mesh geometry={nodes.Shirt_7.geometry} material={materials.bottoms} />
      </group>
    </group>
  )
}

useGLTF.preload('/tshirt2.glb')
