/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/tshirt.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[0.02, 5.4, 0.56]}>
        <mesh geometry={nodes['T-shirt_1'].geometry} material={materials.Shirt} />
        <mesh geometry={nodes['T-shirt_2'].geometry} material={materials.Collar} />
        <mesh geometry={nodes['T-shirt_3'].geometry} material={materials.Sleeve} />
      </group>
    </group>
  )
}

useGLTF.preload('/tshirt.glb')
